In [1]:
import pandas as pd

In [2]:
# Creating a Pandas Series
pd.Series([25000, 0, 4500, 2, 8], index = ['Muammar Qaddafi', 'Mohandas Gandhi', 'Saddam Hussein', 'Kevin Bacon', 'Billy Bob Thornton'],name = 'Max Number Cars Owned')

Muammar Qaddafi       25000
Mohandas Gandhi           0
Saddam Hussein         4500
Kevin Bacon               2
Billy Bob Thornton        8
Name: Max Number Cars Owned, dtype: int64

In [3]:
# A series can also be inputted from a dict
car_dict = {'Muammar Qaddafi': 25000, 'Mohandas Gandhi': 0, 'Saddam Hussein': 4500, 'Kevin Bacon': 2, 'Billy Bob Thornton': 8}
car_owner_series = pd.Series(car_dict, name = 'Max Number Cars Owned')
car_owner_series

Muammar Qaddafi       25000
Mohandas Gandhi           0
Saddam Hussein         4500
Kevin Bacon               2
Billy Bob Thornton        8
Name: Max Number Cars Owned, dtype: int64

In [4]:
car_owner_series["Mohandas Gandhi":"Kevin Bacon"]

Mohandas Gandhi       0
Saddam Hussein     4500
Kevin Bacon           2
Name: Max Number Cars Owned, dtype: int64

To illustrate how series can exploit Numpy style operations. As an example, let’s say that Kevin Bacon bought an extra car and Billy Bob bought two more. We can represent this change as a pandas Series:

In [5]:
delta_cars = {'Mohandas Gandhi': 0, 'Billy Bob Thornton': 2, 'Saddam Hussein': 0, 'Kevin Bacon': 1, 'Muammar Qaddafi': 0}
delta_cars_series = pd.Series(delta_cars, name = 'Max Number Cars Owned')
delta_cars_series

Mohandas Gandhi       0
Billy Bob Thornton    2
Saddam Hussein        0
Kevin Bacon           1
Muammar Qaddafi       0
Name: Max Number Cars Owned, dtype: int64

In [6]:
print(car_owner_series)

Muammar Qaddafi       25000
Mohandas Gandhi           0
Saddam Hussein         4500
Kevin Bacon               2
Billy Bob Thornton        8
Name: Max Number Cars Owned, dtype: int64

In [7]:
new_car_series = car_owner_series + delta_cars_series
print(new_car_series)

Billy Bob Thornton       10
Kevin Bacon               3
Mohandas Gandhi           0
Muammar Qaddafi       25000
Saddam Hussein         4500
Name: Max Number Cars Owned, dtype: int64

In [8]:
new_car_series.index

Index(['Billy Bob Thornton', 'Kevin Bacon', 'Mohandas Gandhi',
       'Muammar Qaddafi', 'Saddam Hussein'],
      dtype='object')

In [9]:
new_car_series.values

array([   10,     3,     0, 25000,  4500], dtype=int64)

In [10]:
new_car_series.name

'Max Number Cars Owned'

In [11]:
# Reassigning the output of the series name
new_car_series.name = 'total cars owned'
new_car_series.name

'total cars owned'

In [12]:
# Data type for Seies values
new_car_series.dtype

dtype('int64')

In [13]:
new_car_series.sort_values(ascending = False)

Muammar Qaddafi       25000
Saddam Hussein         4500
Billy Bob Thornton       10
Kevin Bacon               3
Mohandas Gandhi           0
Name: total cars owned, dtype: int64

# Pandas DataFrames

In [14]:
passengers = pd.read_csv('train.csv', index_col = 'PassengerId')

In [15]:
passengers.head(2)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [16]:
passengers.tail()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [17]:
passengers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    object
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object
 10  Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 83.5+ KB

In [18]:
passengers.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [20]:
passengers.index[0:10]

Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64', name='PassengerId')

In [21]:
passengers.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [22]:
passengers.shape

(891, 11)

# Accessing Data in a DataFrame

In [25]:
passengers['Age']
# passengers.Age is equivalent to passengers['Age']

PassengerId
1      22.0
2      38.0
3      26.0
4      35.0
5      35.0
       ...
887    27.0
888    19.0
889     NaN
890    26.0
891    32.0
Name: Age, Length: 891, dtype: float64

In [27]:
col_list = ['Name', 'Survived', 'Age',]
passengers[col_list]

                                                          Name  Survived   Age
PassengerId
1                                      Braund, Mr. Owen Harris         0  22.0
2            Cumings, Mrs. John Bradley (Florence Briggs Th...         1  38.0
3                                       Heikkinen, Miss. Laina         1  26.0
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)         1  35.0
5                                     Allen, Mr. William Henry         0  35.0
...                                                        ...       ...   ...
887                                      Montvila, Rev. Juozas         0  27.0
888                               Graham, Miss. Margaret Edith         1  19.0
889                   Johnston, Miss. Catherine Helen "Carrie"         0   NaN
890                                      Behr, Mr. Karl Howell         1  26.0
891                                        Dooley, Mr. Patrick         0  32.0

[891 rows x 3 columns]

In [29]:
passengers['Age'][346]

24.0

In [30]:
# .loc[] accessor: - Easily access single row in a DataFrame by named index.
passengers.loc[1]

Survived                          0
Pclass                            3
Name        Braund, Mr. Owen Harris
Sex                            male
Age                            22.0
SibSp                             1
Parch                             0
Ticket                    A/5 21171
Fare                           7.25
Cabin                           NaN
Embarked                          S
Name: 1, dtype: object

In [31]:
row_list = [12, 345, 678, 111]
passengers.loc[row_list]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
345,0,2,"Fox, Mr. Stanley Hubert",male,36.0,0,0,229236,13.0000,NaN,S
678,1,3,"Turja, Miss. Anna Sofia",female,18.0,0,0,4138,9.8417,NaN,S
111,0,1,"Porter, Mr. Walter Chamberlain",male,47.0,0,0,110465,52.0000,C110,S

In [32]:
# Slice rows by index label
passengers.loc[1:10]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [33]:
# Select columns by list
listcol = ['Name', 'Age', 'Survived']
passengers.loc[200:206, listcol]

                                               Name   Age  Survived
PassengerId
200          Yrois, Miss. Henriette ("Mrs Harbeck")  24.0         0
201                  Vande Walle, Mr. Nestor Cyriel  28.0         0
202                             Sage, Mr. Frederick   NaN         0
203                      Johanson, Mr. Jakob Alfred  34.0         0
204                            Youseff, Mr. Gerious  45.5         0
205                        Cohen, Mr. Gurshon "Gus"  18.0         1
206                      Strom, Miss. Telma Matilda   2.0         0

In [34]:
# Slice on columns by name
passengers.loc[200:206, 'Name':'Age']

                                               Name     Sex   Age
PassengerId
200          Yrois, Miss. Henriette ("Mrs Harbeck")  female  24.0
201                  Vande Walle, Mr. Nestor Cyriel    male  28.0
202                             Sage, Mr. Frederick    male   NaN
203                      Johanson, Mr. Jakob Alfred    male  34.0
204                            Youseff, Mr. Gerious    male  45.5
205                        Cohen, Mr. Gurshon "Gus"    male  18.0
206                      Strom, Miss. Telma Matilda  female   2.0

In [38]:
passengers.loc[:, 'Name':'Age']

                                                          Name     Sex   Age
PassengerId
1                                      Braund, Mr. Owen Harris    male  22.0
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
3                                       Heikkinen, Miss. Laina  female  26.0
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
5                                     Allen, Mr. William Henry    male  35.0
...                                                        ...     ...   ...
887                                      Montvila, Rev. Juozas    male  27.0
888                               Graham, Miss. Margaret Edith  female  19.0
889                   Johnston, Miss. Catherine Helen "Carrie"  female   NaN
890                                      Behr, Mr. Karl Howell    male  26.0
891                                        Dooley, Mr. Patrick    male  32.0

[891 rows x 3 columns]

In [39]:
passengers.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [36]:
# Accessing rows by position with .iloc[] accessor
passengers.iloc[1:4, 0:3]

,Survived,Pclass,Name
PassengerId,,,
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
3,1,3,"Heikkinen, Miss. Laina"
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"

In [40]:
passengers.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [42]:
# Renaming classes
passengers.rename(columns = {'Pclass': 'Passenger Class', 'SibSp': 'Siblings/Spouses Aboard', 'Parch': 'Parents/Children Aboard'}, inplace = True)
passengers.columns

Index(['Survived', 'Passenger Class', 'Name', 'Sex', 'Age',
       'Siblings/Spouses Aboard', 'Parents/Children Aboard', 'Ticket', 'Fare',
       'Cabin', 'Embarked'],
      dtype='object')

In [43]:
passengers['Passenger Class']

PassengerId
1      3
2      1
3      3
4      1
5      3
      ..
887    2
888    1
889    3
890    1
891    3
Name: Passenger Class, Length: 891, dtype: int64

In [44]:
[col.strip() for col in passengers.columns]

['Survived',
 'Passenger Class',
 'Name',
 'Sex',
 'Age',
 'Siblings/Spouses Aboard',
 'Parents/Children Aboard',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [45]:
passengers.columns = passengers.columns.str.strip()
print(passengers.columns)

Index(['Survived', 'Passenger Class', 'Name', 'Sex', 'Age',
       'Siblings/Spouses Aboard', 'Parents/Children Aboard', 'Ticket', 'Fare',
       'Cabin', 'Embarked'],
      dtype='object')

In [46]:
passengers['Passenger Class'].head(3)

PassengerId
1    3
2    1
3    3
Name: Passenger Class, dtype: int64

# Removing and Creating New Columns

In [47]:
passengers.drop(columns = 'Cabin', inplace = True)
passengers.columns

Index(['Survived', 'Passenger Class', 'Name', 'Sex', 'Age',
       'Siblings/Spouses Aboard', 'Parents/Children Aboard', 'Ticket', 'Fare',
       'Embarked'],
      dtype='object')

In [48]:
is_embark = (passengers.Embarked == 'S').astype(int)
print(is_embark)
print(is_embark.value_counts())

PassengerId
1      1
2      0
3      1
4      1
5      1
      ..
887    1
888    1
889    1
890    0
891    0
Name: Embarked, Length: 891, dtype: int32
Embarked
1    644
0    247
Name: count, dtype: int64

In [49]:
passengers['is_embark'] = is_embark
passengers.head()

,Survived,Passenger Class,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Ticket,Fare,Embarked,is_embark
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,1
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,0
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,1
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,1

In [50]:
passengers.reset_index(inplace = True)
passengers.head()

,PassengerId,Survived,Passenger Class,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Ticket,Fare,Embarked,is_embark
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,1

In [51]:
passengers.index

RangeIndex(start=0, stop=891, step=1)

In [52]:
passengers.set_index('PassengerId', inplace = True)
passengers.head()

,Survived,Passenger Class,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Ticket,Fare,Embarked,is_embark
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,1
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,0
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,1
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,1

In [53]:
passengers.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       882, 883, 884, 885, 886, 887, 888, 889, 890, 891],
      dtype='int64', name='PassengerId', length=891)

In [54]:
# Dropping rows by index label
passengers.drop(index = [1, 2, 3], inplace = True)
passengers.head()

,Survived,Passenger Class,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Ticket,Fare,Embarked,is_embark
PassengerId,,,,,,,,,,,
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,1
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,Q,0
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S,1
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,S,1

In [55]:
passengers[passengers['Age'] > 60]['Survived']

PassengerId
34     0
55     0
97     0
117    0
171    0
253    0
276    1
281    0
327    0
439    0
457    0
484    1
494    0
546    0
556    0
571    1
626    0
631    1
673    0
746    0
830    1
852    0
Name: Survived, dtype: int64

In [56]:
passengers[passengers['Age'] > 60]['Survived'] + 5

PassengerId
34     5
55     5
97     5
117    5
171    5
253    5
276    6
281    5
327    5
439    5
457    5
484    6
494    5
546    5
556    5
571    6
626    5
631    6
673    5
746    5
830    6
852    5
Name: Survived, dtype: int64

In [57]:
passengers.loc[passengers['Age'] > 60, 'Survived'] += 5
passengers.loc[passengers['Age'] > 60, 'Survived']

PassengerId
34     5
55     5
97     5
117    5
171    5
253    5
276    6
281    5
327    5
439    5
457    5
484    6
494    5
546    5
556    5
571    6
626    5
631    6
673    5
746    5
830    6
852    5
Name: Survived, dtype: int64

In [58]:
df_numeric = passengers.select_dtypes(include = 'number')
df_numeric.info()

<class 'pandas.core.frame.DataFrame'>
Index: 888 entries, 4 to 891
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Survived                 888 non-null    int64
 1   Passenger Class          888 non-null    int64
 2   Age                      711 non-null    float64
 3   Siblings/Spouses Aboard  888 non-null    int64
 4   Parents/Children Aboard  888 non-null    int64
 5   Fare                     888 non-null    float64
 6   is_embark                888 non-null    int32
dtypes: float64(2), int32(1), int64(4)
memory usage: 52.0 KB

In [59]:
df_numeric.mean()

Survived                    0.506757
Passenger Class             2.308559
Age                        29.703474
Siblings/Spouses Aboard     0.522523
Parents/Children Aboard     0.382883
Fare                       32.215643
is_embark                   0.722973
dtype: float64

In [60]:
df_numeric['Fare'].mean()

32.21564301801802

In [61]:
# Calculating the 10th percentile of the numeric columns
df_numeric.quantile(.1)

Survived                    0.00
Passenger Class             1.00
Age                        14.00
Siblings/Spouses Aboard     0.00
Parents/Children Aboard     0.00
Fare                        7.55
is_embark                   0.00
Name: 0.1, dtype: float64

In [62]:
# applied to a Series

df_numeric['Age'].quantile(.1)

14.0

In [63]:
df_numeric.std(ddof=1)

Survived                    0.895913
Passenger Class             0.835686
Age                        14.550290
Siblings/Spouses Aboard     1.104235
Parents/Children Aboard     0.807113
Fare                       49.746361
is_embark                   0.447782
dtype: float64

In [64]:
df_numeric['Age'].std(ddof=1)

14.550289572611852

In [65]:
orig_series = pd.Series([2,5,8], index = ['A', 'B', 'C'])
orig_series

A    2
B    5
C    8
dtype: int64

In [66]:
dict_mapper = {2: 2.5, 5: 7.2, 8: 3.9}
orig_series.map(dict_mapper)

A    2.5
B    7.2
C    3.9
dtype: float64

In [67]:
def func(x):
    return 2*x
orig_series.map(func)

A     4
B    10
C    16
dtype: int64

In [68]:
def bin_fare(input):
    if input <= 10:
        return 'Low Fare'
    elif (input > 10) & (input <= 40):
        return 'Medium Fare'
    elif input > 40:
        return 'High Fare'
    
df_numeric['Fare'].map(bin_fare)

PassengerId
4        High Fare
5         Low Fare
6         Low Fare
7        High Fare
8      Medium Fare
          ...
887    Medium Fare
888    Medium Fare
889    Medium Fare
890    Medium Fare
891       Low Fare
Name: Fare, Length: 888, dtype: object

In [69]:
df_numeric

,Survived,Passenger Class,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare,is_embark
PassengerId,,,,,,,
4,1,1,35.0,1,0,53.1000,1
5,0,3,35.0,0,0,8.0500,1
6,0,3,NaN,0,0,8.4583,0
7,0,1,54.0,0,0,51.8625,1
8,0,3,2.0,3,1,21.0750,1
...,...,...,...,...,...,...,...
887,0,2,27.0,0,0,13.0000,1
888,1,1,19.0,0,0,30.0000,1
889,0,3,NaN,1,2,23.4500,1
890,1,1,26.0,0,0,30.0000,0
891,0,3,32.0,0,0,7.7500,0

In [70]:
orig_series.apply(func)

A     4
B    10
C    16
dtype: int64

In [72]:
# this returns a series [x, x**2, x**3,...up to highest order] for each value
def new_func(x, highest_order = 5):
    
    polynomial_series = pd.Series({'Order ' + str(n+1): x**(n+1) for n in range(highest_order)})
    
    return polynomial_series

orig_series.apply(new_func)

   Order 1  Order 2  Order 3  Order 4  Order 5
A        2        4        8       16       32
B        5       25      125      625     3125
C        8       64      512     4096    32768

In [76]:
import numpy as np
def log_sq_trans(x):
    x_sq = x**2
    summed_sq = np.sum(x_sq)
    logsquaredsum = np.log(1 + summed_sq)
    
    return logsquaredsum

# axis = 0: applies function to each column 
df_numeric[['Age', 'Fare']].apply(log_sq_trans, axis = 1)

PassengerId
4      8.305388
5      7.163019
6      4.284177
7      8.631721
8      6.107369
         ...
887    6.801283
888    7.140453
889    6.311558
890    7.363280
891    6.989393
Length: 888, dtype: float64