In [ ]:
passengers =  [
    {"name": "Alice", "age": 30, "survived": 1},
    {"name": "Bob", "age": 25, "survived": 0},
    {"name": "Charlie", "age": 35, "survived": 1},
    {"name": "David", "age": 28, "survived": 0},
    {"name": "Eve", "age": 22, "survived": 1}
    ]

# Average age of passengers
average_age = sum(passenger['age'] for passenger in passengers if passenger['age'] is not None) / len(passengers)
print(f"Average age of passengers: {average_age:.2f}")

Average age of passengers: 28.00

In [2]:
import pandas as pd
df = pd.DataFrame(passengers)
df

      name  age  survived
0    Alice   30         1
1      Bob   25         0
2  Charlie   35         1
3    David   28         0
4      Eve   22         1

In [3]:
average_age = df['age'].mean()
average_age

28.0

In [4]:
ages = pd.Series([30, 25, 35, 28, 22])
print(ages)

0    30
1    25
2    35
3    28
4    22
dtype: int64

In [5]:
ages[2]

35

In [6]:
data = {
    'name' : ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'age' : [30, 25, 35, 28, 22],
    'Score' : [85, 90, 78, 92, 88]
}

df = pd.DataFrame(data)
print(df)

      name  age  Score
0    Alice   30     85
1      Bob   25     90
2  Charlie   35     78
3    David   28     92
4      Eve   22     88

In [23]:
df = pd.read_csv('train.csv')
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
df = pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
# Reading a specific column
ages = df['Age']
name = df['Name']
print(ages.head())
print(name.head())

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [15]:
df = pd.read_csv('train.csv', usecols=['Survived', 'Sex'])
df.head()

   Survived     Sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

In [14]:
df = pd.read_csv('train.csv', index_col='PassengerId', usecols=['PassengerId', 'Ticket', 'Survived', 'Sex'])
df.head()

             Survived     Sex            Ticket
PassengerId
1                   0    male         A/5 21171
2                   1  female          PC 17599
3                   1  female  STON/O2. 3101282
4                   1  female            113803
5                   0    male            373450

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Sex       891 non-null    object
dtypes: int64(1), object(1)
memory usage: 14.1+ KB

In [19]:
df.describe()

         Survived
count  891.000000
mean     0.383838
std      0.486592
min      0.000000
25%      0.000000
50%      0.000000
75%      1.000000
max      1.000000

In [24]:
# Accessing mutiple columns
df[['Name', 'Fare', 'Survived', 'Cabin']]

,Name,Fare,Survived,Cabin
0,"Braund, Mr. Owen Harris",7.2500,0,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",71.2833,1,C85
2,"Heikkinen, Miss. Laina",7.9250,1,NaN
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",53.1000,1,C123
4,"Allen, Mr. William Henry",8.0500,0,NaN
...,...,...,...,...
886,"Montvila, Rev. Juozas",13.0000,0,NaN
887,"Graham, Miss. Margaret Edith",30.0000,1,B42
888,"Johnston, Miss. Catherine Helen ""Carrie""",23.4500,0,NaN
889,"Behr, Mr. Karl Howell",30.0000,1,C148
890,"Dooley, Mr. Patrick",7.7500,0,NaN

In [25]:
# Accessing the survivors
survivors = df[df['Survived'] == 1]
survivors

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [27]:
df[df['Age'] >= 50]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
...,...,...,...,...,...,...,...,...,...,...,...,...
820,821,1,1,"Hays, Mrs. Charles Melville (Clara Jennings Gr...",female,52.0,1,1,12749,93.5000,B69,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

In [29]:
# drop all rows with missing values
df.dropna(inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 183 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  183 non-null    int64
 1   Survived     183 non-null    int64
 2   Pclass       183 non-null    int64
 3   Name         183 non-null    object
 4   Sex          183 non-null    object
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64
 7   Parch        183 non-null    int64
 8   Ticket       183 non-null    object
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object
 11  Embarked     183 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 18.6+ KB

In [30]:
# Find females who survived
df[(df['Survived'] == 1) & (df['Sex'] == 'female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
853,854,1,1,"Lines, Miss. Mary Conover",female,16.0,0,1,PC 17592,39.4000,D28,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [39]:
# Accessing data using loc and iloc
# Using loc to access rows by label
df.loc[:5, 'Name']

1    Cumings, Mrs. John Bradley (Florence Briggs Th...
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
Name: Name, dtype: object

In [33]:
df.iloc[0]

PassengerId                                                    2
Survived                                                       1
Pclass                                                         1
Name           Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                       female
Age                                                         38.0
SibSp                                                          1
Parch                                                          0
Ticket                                                  PC 17599
Fare                                                     71.2833
Cabin                                                        C85
Embarked                                                       C
Name: 1, dtype: object

In [37]:
df.iloc[0:6, 4]

1     female
3     female
6       male
10    female
11    female
21      male
Name: Sex, dtype: object

In [40]:
df.iloc[0:5, 0:3]

    PassengerId  Survived  Pclass
1             2         1       1
3             4         1       1
6             7         0       1
10           11         1       3
11           12         1       1

In [42]:
df.loc[:, 'Age']

1      38.0
3      35.0
6      54.0
10      4.0
11     58.0
       ...
871    47.0
872    33.0
879    56.0
887    19.0
889    26.0
Name: Age, Length: 183, dtype: float64

In [43]:
df.loc[0:3, 'Name':'Age']

                                                Name     Sex   Age
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0