In [1]:
# How to establish a connection to the database
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('bookstore.db')

print(conn)  # This will print the connection object, confirming that the connection was established successfully.

<sqlite3.Connection object at 0x0000020D36EDBB50>

In [2]:
# Using sql without pandas
cursor = conn.cursor()
cursor.execute("SELECT * FROM books")
results = cursor.fetchall()
print(results)

[(1, 'Things Fall Apart', 1, 'Literary Fiction', 12.99, 45, 1958), (2, 'Arrow of God', 1, 'Literary Fiction', 11.99, 30, 1964), (3, 'A Grain of Wheat', 2, 'Historical Fiction', 13.99, 20, 1967), (4, 'Petals of Blood', 2, 'Political Fiction', 14.99, 15, 1977), (5, 'Purple Hibiscus', 3, 'Literary Fiction', 13.5, 60, 2003), (6, 'Half of a Yellow Sun', 3, 'Historical Fiction', 14.5, 55, 2006), (7, 'Americanah', 3, 'Contemporary Fiction', 15.99, 40, 2013), (8, "Death and the King's Horseman", 4, 'Drama', 10.99, 25, 1975), (9, 'Our Sister Killjoy', 5, 'Literary Fiction', 11.5, 18, 1977), (10, 'Second Class Citizen', 6, 'Literary Fiction', 12.5, 22, 1974), (11, 'African Psycho', 7, 'Thriller', 13.0, 35, 2003), (12, 'We Need New Names', 8, 'Literary Fiction', 14.0, 28, 2013), (13, 'Open City', 9, 'Literary Fiction', 13.5, 33, 2011), (14, 'The River Between', 2, 'Literary Fiction', 10.99, 12, 1965), (15, 'Weep Not Child', 2, 'Literary Fiction', 10.5, 10, 1964)]

In [3]:
# Using sql with pandas
# Read data from the database into a pandas DataFrame
pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table';", # This query retrieves the names of all tables in the database
    conn
)

        name
0    authors
1      books
2  customers
3     orders

In [4]:
# Selecting all from authors
pd.read_sql("SELECT * FROM authors;", conn)

   author_id                      name   country  birth_year
0          1             Chinua Achebe   Nigeria        1930
1          2         Ngũgĩ wa Thiong'o     Kenya        1938
2          3  Chimamanda Ngozi Adichie   Nigeria        1977
3          4              Wole Soyinka   Nigeria        1934
4          5             Ama Ata Aidoo     Ghana        1942
5          6            Buchi Emecheta   Nigeria        1944
6          7           Alain Mabanckou     Congo        1966
7          8         NoViolet Bulawayo  Zimbabwe        1981
8          9                 Teju Cole   Nigeria        1975
9         10             Mariam Konate      Mali        1985

In [5]:
pd.read_sql("SELECT * FROM books;", conn)

,book_id,title,author_id,genre,price,stock,published_year
0,1,Things Fall Apart,1,Literary Fiction,12.99,45,1958
1,2,Arrow of God,1,Literary Fiction,11.99,30,1964
2,3,A Grain of Wheat,2,Historical Fiction,13.99,20,1967
3,4,Petals of Blood,2,Political Fiction,14.99,15,1977
4,5,Purple Hibiscus,3,Literary Fiction,13.50,60,2003
5,6,Half of a Yellow Sun,3,Historical Fiction,14.50,55,2006
6,7,Americanah,3,Contemporary Fiction,15.99,40,2013
7,8,Death and the King's Horseman,4,Drama,10.99,25,1975
8,9,Our Sister Killjoy,5,Literary Fiction,11.50,18,1977
9,10,Second Class Citizen,6,Literary Fiction,12.50,22,1974
10,11,African Psycho,7,Thriller,13.00,35,2003
11,12,We Need New Names,8,Literary Fiction,14.00,28,2013
12,13,Open City,9,Literary Fiction,13.50,33,2011
13,14,The River Between,2,Literary Fiction,10.99,12,1965
14,15,Weep Not Child,2,Literary Fiction,10.50,10,1964

In [12]:
pd.read_sql("SELECT * FROM books WHERE published_year > 1990;", conn)

,book_id,title,author_id,genre,price,stock,published_year
0,5,Purple Hibiscus,3,Literary Fiction,13.50,60,2003
1,6,Half of a Yellow Sun,3,Historical Fiction,14.50,55,2006
2,7,Americanah,3,Contemporary Fiction,15.99,40,2013
3,11,African Psycho,7,Thriller,13.00,35,2003
4,12,We Need New Names,8,Literary Fiction,14.00,28,2013
5,13,Open City,9,Literary Fiction,13.50,33,2011

In [6]:
pd.read_sql("SELECT * FROM customers;", conn)

,customer_id,name,email,city,country,member_since
0,1,Amara Diallo,amara@email.com,Nairobi,Kenya,2020
1,2,Kofi Mensah,kofi@email.com,Accra,Ghana,2019
2,3,Fatima Nour,fatima@email.com,Cairo,Egypt,2021
3,4,Emeka Obi,emeka@email.com,Lagos,Nigeria,2018
4,5,Zanele Mokoena,zanele@email.com,Johannesburg,South Africa,2022
5,6,Tariq Hassan,tariq@email.com,Nairobi,Kenya,2020
6,7,Yemi Adeyemi,yemi@email.com,Abuja,Nigeria,2019
7,8,Aisha Kamara,aisha@email.com,Freetown,Sierra Leone,2021
8,9,Kwame Asante,kwame@email.com,Kumasi,Ghana,2023
9,10,Leilah Mwangi,leilah@email.com,Mombasa,Kenya,2020
10,11,Seko Touré,seko@email.com,Conakry,Guinea,2022
11,12,Binta Jallow,binta@email.com,Banjul,Gambia,2021

In [7]:
pd.read_sql("SELECT * FROM orders;", conn)

    order_id  customer_id  book_id  quantity  order_date
0          1            1        5         2  2024-01-15
1          2            2        1         1  2024-01-18
2          3            3        6         1  2024-01-20
3          4            4        7         3  2024-02-01
4          5            5       12         1  2024-02-03
5          6            1        6         1  2024-02-10
6          7            6        3         2  2024-02-14
7          8            7        5         1  2024-02-20
8          9            2        7         1  2024-03-01
9         10            8        1         2  2024-03-05
10        11            9       13         1  2024-03-10
11        12            4        2         1  2024-03-12
12        13           10        5         2  2024-03-15
13        14            3        8         1  2024-03-18
14        15           11       11         1  2024-03-22
15        16            1        3         1  2024-04-01
16        17            6        6         2  2024-04-05
17        18            5        7         1  2024-04-08
18        19           12        4         1  2024-04-10
19        20            7        9         1  2024-04-15
20        21            2       14         2  2024-04-20
21        22            4        5         1  2024-04-22
22        23           10        7         1  2024-04-25
23        24            8        6         1  2024-05-01
24        25            3        3         1  2024-05-05

In [8]:
pd.read_sql("SELECT author_id, name, country FROM authors;", conn)

   author_id                      name   country
0          1             Chinua Achebe   Nigeria
1          2         Ngũgĩ wa Thiong'o     Kenya
2          3  Chimamanda Ngozi Adichie   Nigeria
3          4              Wole Soyinka   Nigeria
4          5             Ama Ata Aidoo     Ghana
5          6            Buchi Emecheta   Nigeria
6          7           Alain Mabanckou     Congo
7          8         NoViolet Bulawayo  Zimbabwe
8          9                 Teju Cole   Nigeria
9         10             Mariam Konate      Mali

In [9]:
# rename columns using AS (aliasing): create temporary names for columns or tables to make the output more readable
pd.read_sql("SELECT title AS book_title, price AS price_usd FROM books;", conn)

                       book_title  price_usd
0               Things Fall Apart      12.99
1                    Arrow of God      11.99
2                A Grain of Wheat      13.99
3                 Petals of Blood      14.99
4                 Purple Hibiscus      13.50
5            Half of a Yellow Sun      14.50
6                      Americanah      15.99
7   Death and the King's Horseman      10.99
8              Our Sister Killjoy      11.50
9            Second Class Citizen      12.50
10                 African Psycho      13.00
11              We Need New Names      14.00
12                      Open City      13.50
13              The River Between      10.99
14                 Weep Not Child      10.50

In [10]:
# Select author and name from authors table give name an alias of author_name
pd.read_sql("SELECT author_id, name AS author_name FROM authors;", conn)

   author_id               author_name
0          1             Chinua Achebe
1          2         Ngũgĩ wa Thiong'o
2          3  Chimamanda Ngozi Adichie
3          4              Wole Soyinka
4          5             Ama Ata Aidoo
5          6            Buchi Emecheta
6          7           Alain Mabanckou
7          8         NoViolet Bulawayo
8          9                 Teju Cole
9         10             Mariam Konate

In [11]:
pd.read_sql("SELECT title, genre, price FROM books WHERE genre = 'Literary Fiction';", conn)

                  title             genre  price
0     Things Fall Apart  Literary Fiction  12.99
1          Arrow of God  Literary Fiction  11.99
2       Purple Hibiscus  Literary Fiction  13.50
3    Our Sister Killjoy  Literary Fiction  11.50
4  Second Class Citizen  Literary Fiction  12.50
5     We Need New Names  Literary Fiction  14.00
6             Open City  Literary Fiction  13.50
7     The River Between  Literary Fiction  10.99
8        Weep Not Child  Literary Fiction  10.50

In [14]:
pd.read_sql("SELECT title, genre, price FROM books WHERE genre = 'Literary Fiction' AND price < 12;", conn)

                title             genre  price
0        Arrow of God  Literary Fiction  11.99
1  Our Sister Killjoy  Literary Fiction  11.50
2   The River Between  Literary Fiction  10.99
3      Weep Not Child  Literary Fiction  10.50

In [15]:
pd.read_sql("SELECT * FROM books WHERE genre = 'Literary Fiction' OR price < 12;", conn)

,book_id,title,author_id,genre,price,stock,published_year
0,1,Things Fall Apart,1,Literary Fiction,12.99,45,1958
1,2,Arrow of God,1,Literary Fiction,11.99,30,1964
2,5,Purple Hibiscus,3,Literary Fiction,13.50,60,2003
3,8,Death and the King's Horseman,4,Drama,10.99,25,1975
4,9,Our Sister Killjoy,5,Literary Fiction,11.50,18,1977
5,10,Second Class Citizen,6,Literary Fiction,12.50,22,1974
6,12,We Need New Names,8,Literary Fiction,14.00,28,2013
7,13,Open City,9,Literary Fiction,13.50,33,2011
8,14,The River Between,2,Literary Fiction,10.99,12,1965
9,15,Weep Not Child,2,Literary Fiction,10.50,10,1964

In [16]:
# IN and Between
pd.read_sql("SELECT title, genre, price FROM books WHERE genre IN ('Literary Fiction', 'Historical Fiction');", conn)

                   title               genre  price
0      Things Fall Apart    Literary Fiction  12.99
1           Arrow of God    Literary Fiction  11.99
2       A Grain of Wheat  Historical Fiction  13.99
3        Purple Hibiscus    Literary Fiction  13.50
4   Half of a Yellow Sun  Historical Fiction  14.50
5     Our Sister Killjoy    Literary Fiction  11.50
6   Second Class Citizen    Literary Fiction  12.50
7      We Need New Names    Literary Fiction  14.00
8              Open City    Literary Fiction  13.50
9      The River Between    Literary Fiction  10.99
10        Weep Not Child    Literary Fiction  10.50

In [17]:
pd.read_sql(
    """SELECT * FROM customers WHERE member_since BETWEEN 2019 AND 2020;""",
    conn
)

,customer_id,name,email,city,country,member_since
0,1,Amara Diallo,amara@email.com,Nairobi,Kenya,2020
1,2,Kofi Mensah,kofi@email.com,Accra,Ghana,2019
2,6,Tariq Hassan,tariq@email.com,Nairobi,Kenya,2020
3,7,Yemi Adeyemi,yemi@email.com,Abuja,Nigeria,2019
4,10,Leilah Mwangi,leilah@email.com,Mombasa,Kenya,2020

In [18]:
pd.read_sql("SELECT * FROM customers WHERE name LIKE 'A%';", conn)

,customer_id,name,email,city,country,member_since
0,1,Amara Diallo,amara@email.com,Nairobi,Kenya,2020
1,8,Aisha Kamara,aisha@email.com,Freetown,Sierra Leone,2021

In [19]:
pd.read_sql("""
SELECT * FROM books ORDER BY price ASC LIMIT 5;
""",
    conn
)

,book_id,title,author_id,genre,price,stock,published_year
0,15,Weep Not Child,2,Literary Fiction,10.50,10,1964
1,8,Death and the King's Horseman,4,Drama,10.99,25,1975
2,14,The River Between,2,Literary Fiction,10.99,12,1965
3,9,Our Sister Killjoy,5,Literary Fiction,11.50,18,1977
4,2,Arrow of God,1,Literary Fiction,11.99,30,1964

In [20]:
pd.read_sql("""SELECT COUNT(*) AS total_books FROM books;""", conn)

   total_books
0           15

In [21]:
pd.read_sql("SELECT ROUND(AVG(price), 2) AS avg_price FROM books;", conn)

   avg_price
0       13.0

In [23]:
pd.read_sql("SELECT SUM(quantity) AS total_quantity FROM orders;", conn)

   total_quantity
0              33

In [24]:
# GROUP BY and HAVING
pd.read_sql("""SELECT genre, COUNT(*) AS num_books FROM books GROUP BY genre HAVING num_books > 1;
""", conn)

                genre  num_books
0  Historical Fiction          2
1    Literary Fiction          9

In [27]:
# select genre, title, avg(price), sum(price) of books group by genre, filter if price is greater than avg price
pd.read_sql("""SELECT genre, title, AVG(price) AS avg_price, SUM(price) AS total_price
    FROM books
    GROUP BY genre
    HAVING price > (SELECT AVG(price) FROM books);
    """, conn)

                  genre             title  avg_price  total_price
0  Contemporary Fiction        Americanah     15.990        15.99
1    Historical Fiction  A Grain of Wheat     14.245        28.49
2     Political Fiction   Petals of Blood     14.990        14.99
3              Thriller    African Psycho     13.000        13.00